name: travel_impressions
version: 1.0.0
author: Dzenan Ridjanovic <dzenanr@gmail.com>
description: travel_impressions application that uses dartling for its model.
homepage: http://ondart.me/
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=0.8.10+8 <2.0.0'
dependencies:
  browser: any
  dartling: any
  dartling_default_app: any
